# Generated by Django 5.2.6 on 2025-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('mastodon', 'Mastodon')], max_length=50)),
                ('url', models.URLField()),
                ('is_visible', models.BooleanField(default=True, help_text='Check to display this link on the site')),
            ],
        ),
    ]
