# Generated by Django 5.2.6 on 2025-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the term', null=True, upload_to='glossary_images/'),
        ),
        migrations.AddField(
            model_name='term',
            name='url',
            field=models.URLField(blank=True, help_text='Optional external link for more info', null=True),
        ),
    ]
