# Generated by Django 5.2.6 on 2025-09-16 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_term_image_term_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='alphabet',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image', null=True, upload_to='glossary_images/'),
        ),
        migrations.AlterField(
            model_name='term',
            name='url',
            field=models.URLField(blank=True, help_text='Optional external link', null=True),
        ),
    ]
