# Generated by Django 5.2.6 on 2025-10-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_term_alphabet_alter_term_image_alter_term_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='is_featured',
        ),
    ]
