# Generated by Django 5.2.6 on 2025-09-10 14:40

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Entry Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project', 'Project'), ('tutorial', 'Tutorial'), ('post', 'Post')], default='post', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('excerpt', models.CharField(blank=True, help_text='Short summary or description for previews and SEO', max_length=160)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='entry_images/')),
                ('cover_alt', models.CharField(blank=True, help_text='Accessible alt text for cover image', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text="0–100% progress (only shown if status is 'in progress')")),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('reading_time', models.PositiveIntegerField(default=0, editable=False, help_text='Estimated reading time in minutes')),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='entry_categories', to='content.entrycategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='entry_tags', to='content.entrytag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('demo', 'Demo'), ('reference', 'Reference')], default='reference', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class (e.g. 'bi bi-rocket')", max_length=50)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.entry')),
            ],
        ),
    ]
