# Generated by Django 5.2.6 on 2025-09-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.entry',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.entry',),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.entry',),
        ),
    ]
