# Generated by Django 5.2.6 on 2025-09-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post_project_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.entry')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.material')),
            ],
            options={
                'unique_together': {('entry', 'material')},
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='materials',
            field=models.ManyToManyField(related_name='entries', through='content.EntryMaterial', to='content.material'),
        ),
    ]
