# Generated by Django 5.2.6 on 2025-09-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_material_entrymaterial_entry_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='material_icons/'),
        ),
    ]
