# Generated by Django 5.2.6 on 2025-09-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_material_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrytag',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tags', to='content.entrycategory'),
        ),
    ]
