# Generated by Django 5.2.6 on 2025-09-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_entrytag_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.entry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'ip_address', 'session_key'), name='unique_anon_like')],
            },
        ),
    ]
